[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[[constraint]]
  name = "github.com/kylelemons/go-gypsy"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/ziutek/mymysql"
  branch = "master"

[[constraint]]
  name = "modernc.org/sqlite"
  branch = "master"
